### PR TITLE
Fix KdocMethods

### LINKED ISSUE #74: Fix KdocMethods#addKdocTemplate
KDocs added by `KDocMethods` rule are not properly indented by `IndentationRule`. This is probably because KDoc template is added as `LeafPsiElement`, while it should be a `CompositeElement`.
Example of `CompositeElement` construction can be found in KdocUtils: `ASTNode.insertTagBefore`.
Once this is fixed, one should try applying `KDocMethods` and `IndentationRule` simultaneously. Such case should also be added in #50 .

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
  Added KDoc template as CompositeElement
  Changed tests
  closes #74

### CODE REVIEW

**Review by petertrr — COMMENTED** [review]
Could you please check how this now cooperates with IndentationRule? The problem with adding KDoc as `LeafElement` was that indentation was not applied to it later. You can create a simple file with function without KDoc, run diktat on it and check if created KDoc is indented correctly.

**Comment by petertrr** [comment]
> Could you please check how this now cooperates with IndentationRule? The problem with adding KDoc as `LeafElement` was that indentation was not applied to it later. You can create a simple file with function without KDoc, run diktat on it and check if created KDoc is indented correctly.

**Comment by kentr0w** [comment]
> Could you please check how this now cooperates with IndentationRule? The problem with adding KDoc as `LeafElement` was that indentation was not applied to it later. You can create a simple file with function without KDoc, run diktat on it and check if created KDoc is indented correctly.

I've checked it before push.

**Review by petertrr — APPROVED** [review]
LGTM

**Pull request merged**
